### ISSUE TITLE
LEDOutput.cpp: Checks against negativity on unsigned values

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [seanlano/wi-led#10]
There are multiple sections of code where a value is checked for negativity, when the value is an unsigned type (such as the line `if (inTimeMillis < 0){inTimeMillis = abs(inTimeMillis);}`).

It would be a very minor performance gain if these checks were simply removed (as they serve no purpose in the current code).

**Comment by seanlano** [comment]
Fair point, I will review this.
