### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [seanlano/wi-led#12]
Currently there are no examples of how to implement a system based on these libraries. It would be good to have a basic sketch showing how to utilise these libraries to combine a rotary encoder with an LED driver.

**Comment by seanlano** [comment]
Agreed - more detail is needed.

**Comment by seanlano** [comment]
There are actually some examples now - given that the features aren't complete yet, these aren't working examples - but they can be compiled and flashed to the appropriate hardware and they will run. So I'll close this issue. As more work is done, the examples will continue to be updated.
