### ISSUE TITLE
LEDOutput.cpp: __state_dim_level_goal is not checked for sanity

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [seanlano/wi-led#9]
If the `__state_dim_level_goal` got itself into an illogical state (`__state_dim_level_goal >= NUM_DIM_STEPS`), then it could potentially get stuck that way for an extended period of time.

It would make more sense if in both the `LEDOutput::setDimStepUp()` and `LEDOutput::setDimStepDown()` functions, the `default` cases checked for sanity, and set to a logical value if it was found to be unacceptable.

**Comment by seanlano** [comment]
This is a valid point, thanks. I'll add such a check to the code.
